CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "email" varchar,
  "role" varchar
);

CREATE TABLE "Doctor" (
  "id" int PRIMARY KEY,
  "full_name" varchar,
  "credentials" varchar,
  "specialties" varchar
);

CREATE TABLE "Patient" (
  "id" int PRIMARY KEY,
  "full_name" varchar,
  "medical_history" text
);

CREATE TABLE "Appointment" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" int,
  "doctor_id" int,
  "date" datetime,
  "status" varchar
);

CREATE TABLE "Notification" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "message" text,
  "type" varchar,
  "date" datetime
);

CREATE TABLE "Sample" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "appointment_id" int,
  "type" varchar,
  "collection_date" datetime,
  "analysis_date" datetime,
  "status" varchar
);

CREATE TABLE "HealthInformation" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "content" text,
  "disease" varchar
);

ALTER TABLE "Doctor" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

ALTER TABLE "Patient" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

ALTER TABLE "Appointment" ADD FOREIGN KEY ("patient_id") REFERENCES "Patient" ("id");

ALTER TABLE "Appointment" ADD FOREIGN KEY ("doctor_id") REFERENCES "Doctor" ("id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "Sample" ADD FOREIGN KEY ("appointment_id") REFERENCES "Appointment" ("id");
